In [3]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [4]:
import numpy
n=numpy.arange(27)

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [14]:
m=numpy.asarray([[123,12,123,12,33],[123,12,123,12,33],[123,12,123,12,33]])

In [15]:
m

array([[123,  12, 123,  12,  33],
       [123,  12, 123,  12,  33],
       [123,  12, 123,  12,  33]])

In [16]:
type(m)

numpy.ndarray

In [17]:
import cv2

In [18]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
cv2.imwrite("newsmallgray.png",im_g)

True

In [20]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [22]:
im_g[2,4]

182

In [24]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [25]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [26]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [27]:
ims=numpy.hstack((im_g,im_g))

In [28]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [29]:
ims=numpy.vstack((im_g,im_g))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
lst=numpy.hsplit(ims,5)

In [32]:
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [34]:
type(lst)

list